#!/bin/bash
# OMARCLOCK - Minimal Futuristic Clock Wrapper
# Autogenerated by omarchy-theme-watcher
# Do not edit directly - changes will be overwritten when theme updates

# Hot color scheme (yellow/red/orange focus)
PRIMARY_COLOR="{{ bright_yellow | default(value="#ffe64d") }}"      # Bright yellow (primary)
ACCENT_COLOR="{{ yellow | default(value="#fcee0a") }}"              # Electric yellow
GLOW_COLOR="{{ bright_red | default(value="#ff2d6f") }}"            # Hot red accent

# Clock settings
CLOCK_SIZE="{{ size | default(value="1") }}"                        # Size of the digits (1-5, 1 is safest for small terminals)
CLOCK_MODE="{{ mode | default(value="clock") }}"                    # Mode: clock, timer, stopwatch, countdown
CLOCK_STYLE="{{ style | default(value="minimal") }}"                # Style: minimal, default, detailed, compact, time-only

# Terminal colors
RESET='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'

# Convert hex to RGB
hex_to_rgb() {
    local hex=$1
    hex=${hex#\#}
    printf "%d;%d;%d" 0x${hex:0:2} 0x${hex:2:2} 0x${hex:4:2}
}

PRIMARY_RGB=$(hex_to_rgb "$PRIMARY_COLOR")
ACCENT_RGB=$(hex_to_rgb "$ACCENT_COLOR")
GLOW_RGB=$(hex_to_rgb "$GLOW_COLOR")

# Check terminal size
TERM_COLS=$(tput cols 2>/dev/null || echo 80)
TERM_LINES=$(tput lines 2>/dev/null || echo 24)

# Calculate required space (rough estimate)
# Size 1: ~15 lines, Size 2: ~25 lines, Size 3: ~35 lines
REQUIRED_LINES=$((15 + (CLOCK_SIZE - 1) * 10))
REQUIRED_COLS=$((40 + (CLOCK_SIZE - 1) * 20))

if [ "$TERM_LINES" -lt "$REQUIRED_LINES" ] || [ "$TERM_COLS" -lt "$REQUIRED_COLS" ]; then
    clear
    echo ""
    echo -e " \033[38;2;${GLOW_RGB}m✗\033[0m \033[38;2;${PRIMARY_RGB}mOmarclock${RESET} \033[2m// terminal too small\033[0m"
    echo ""
    echo -e " Terminal: ${TERM_COLS}x${TERM_LINES}"
    echo -e " Required: ${REQUIRED_COLS}x${REQUIRED_LINES} (for size ${CLOCK_SIZE})"
    echo ""
    echo -e " \033[2mTip: Resize terminal or use smaller size:\033[0m"
    echo -e " \033[2m  omarclock --size 1\033[0m"
    echo ""
    exit 1
fi

# Minimal header - no boxes, no date
clear
echo ""
echo -e " \033[38;2;${GLOW_RGB}m▸\033[38;2;${PRIMARY_RGB}m OMARCLOCK ${RESET}\033[2m// time.sync\033[0m"
echo ""

# Build clock command based on style
CLOCK_ARGS=""
case "$CLOCK_STYLE" in
    "minimal")
        # Just time, no date, no seconds
        CLOCK_ARGS="--no-date --no-seconds"
        ;;
    "compact")
        # No date, with seconds
        CLOCK_ARGS="--no-date"
        ;;
    "time-only")
        # No date, no seconds (ultra minimal)
        CLOCK_ARGS="--no-date --no-seconds"
        ;;
    "detailed")
        # Show everything including milliseconds
        CLOCK_ARGS="--millis"
        ;;
    "default"|*)
        # Show date and time with seconds (tclock default)
        CLOCK_ARGS=""
        ;;
esac

# Launch tclock with hot yellow color
# Global options (--color, --size) must come BEFORE the subcommand
exec tclock --color "$PRIMARY_COLOR" --size "$CLOCK_SIZE" $CLOCK_MODE $CLOCK_ARGS
