#!/bin/bash
# OMARCLOCK - Clean themed clock wrapper
# Autogenerated by omarchy-theme-watcher

# Theme color (from Omarchy theme)
PRIMARY_COLOR="{{ bright_cyan | default(value="#00d4ff") }}"

# Default settings - clean cyberpunk style
TCLOCK_ARGS="-color $PRIMARY_COLOR -no-seconds -color-disc none -truecolor"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --seconds|-s)
            TCLOCK_ARGS="${TCLOCK_ARGS/-no-seconds/}"
            shift
            ;;
        --box|-b)
            TCLOCK_ARGS="$TCLOCK_ARGS -box"
            shift
            ;;
        --disc|-d)
            TCLOCK_ARGS="$TCLOCK_ARGS -color-disc $PRIMARY_COLOR"
            shift
            ;;
        --24)
            TCLOCK_ARGS="$TCLOCK_ARGS -24"
            shift
            ;;
        --analog|-a)
            TCLOCK_ARGS="$TCLOCK_ARGS -analog"
            shift
            ;;
        --countdown)
            TCLOCK_ARGS="$TCLOCK_ARGS -countdown $2"
            shift 2
            ;;
        *)
            # Pass through any other tclock args directly
            TCLOCK_ARGS="$TCLOCK_ARGS $1"
            shift
            ;;
    esac
done

# Launch tclock with theme color
exec tclock $TCLOCK_ARGS
